server:
  port: 8086
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kulkarnishruti4/micro-configuration-service
          clone-on-start: true
          
    
      